highlighter: pygments
paginate: 10
markdown: kramdown
host: 0.0.0.0

subscribe_rss: /atom.xml
kramdown:
  input: GFM
  hard_wrap: false

home_url: "http://bakyeono-plus21.github.io"

sass:
    sass_dir: css
